version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432